cycle_outlet:
  target:
    entity:
      integration: middle_atlantic_racklink
      domain: switch

cycle_all_outlets:
  target:
    entity:
      integration: middle_atlantic_racklink
      domain: switch

set_outlet_name:
  target:
    entity:
      integration: middle_atlantic_racklink
      domain: switch
  fields:
    name:
      required: true
      example: "Server"
      selector:
        text:

set_pdu_name:
  target:
    entity:
      integration: middle_atlantic_racklink
      domain: switch
  fields:
    name:
      required: true
      example: "Rack Power"
      selector:
        text:
