name: Code Quality

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  code-quality:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black isort mypy
      - name: Run black
        run: |
          black --check custom_components/middle_atlantic_racklink
      - name: Run isort
        run: |
          isort --check-only --profile=black custom_components/middle_atlantic_racklink/**/*.py
      - name: Run pylint
        run: |
          pylint custom_components/middle_atlantic_racklink
      - name: Run mypy
        run: |
          mypy custom_components/middle_atlantic_racklink
