name: Basic Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio
          pip install homeassistant

      - name: Run basic validation
        run: |
          python -m pytest tests/test_binary_sensor.py tests/test_sensor.py tests/test_switch.py tests/test_config_flow.py -v
        env:
          PYTHONPATH: ${{ github.workspace }}
