name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: Validate with hassfest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-latest
    name: Validate with HACS

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Checks

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Lint with pylint
        run: |
          pylint custom_components/middle_atlantic_racklink --exit-zero --output-format=text --reports=no

      - name: Security scan with bandit
        run: |
          bandit -r custom_components/middle_atlantic_racklink -f json -o bandit-report.json || true

      - name: Upload bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.json

  compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        home-assistant-version: ["2023.1.0", "2023.12.0", "2024.1.0"]

    name: Test HA ${{ matrix.home-assistant-version }} compatibility

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install HA ${{ matrix.home-assistant-version }}
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant==${{ matrix.home-assistant-version }}
          pip install -r requirements-test.txt

      - name: Test integration loading
        run: |
          python -c "
          import sys
          sys.path.insert(0, '.')
          try:
              from custom_components.middle_atlantic_racklink import async_setup_entry
              print('✅ Integration loads successfully with HA ${{ matrix.home-assistant-version }}')
          except Exception as e:
              print(f'❌ Failed to load integration: {e}')
              sys.exit(1)
          "
